apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coffeebuddy-kong
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/strip-path: "true"
    konghq.com/plugins: coffeebuddy-rate-limit
spec:
  rules:
    - host: coffeebuddy.slack.internal.example.com
      http:
        paths:
          - path: /slack
            pathType: Prefix
            backend:
              service:
                name: coffeebuddy
                port:
                  number: 80